baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "Mekhid Teaching Co."
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "MTC"
description = "who sees this?"
[params.banner]
heading = "Join a community of learners from around the world and get support from our experienced instructors."
image = "images/books8.jpg"
[params.blog]
heading = "Choose from a variety of flexible scheduling options to fit your learning needs and schedule."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Take your education to the next level with our cutting-edge online courses and resources."
enable = true
title = "Contact us for more information."
[params.footer]
address = "123 Main Street <br> New York, NY 10001"
content = "Be the best version of yourself, today."
copyright = "Copyright &copy; 2023 a Mekhid Teaching Co. Ltd. "
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
title = "What are you waiting for?"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/books9.jpg"
[[params.gallery.gallery_item]]
image = "images/books10.jpg"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
